"""site_tables

Revision ID: 3473f3973bf8
Revises: 
Create Date: 2019-11-02 18:42:18.130062

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3473f3973bf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.Column('password', sa.String(length=60), nullable=False),
                    sa.Column('last_login', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('food_item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.Column('description', sa.String(length=120), nullable=True),
                    sa.Column('price', sa.Float(precision=2), nullable=False),
                    sa.Column('type', sa.String(length=64), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('menu_file',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=60), nullable=False),
                    sa.Column('path_to_file', sa.String(length=60), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('role',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=True),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('option',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.Column('price', sa.Float(precision=2), nullable=False),
                    sa.Column('type', sa.String(length=64), nullable=False),
                    sa.ForeignKeyConstraint(['type'], ['food_item.type'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('roles_users',
                    sa.Column('customer_id', sa.Integer(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('option')
    op.drop_table('role')
    op.drop_table('menu_file')
    op.drop_table('food_item')
    op.drop_table('customer')
    # ### end Alembic commands ###
