"""site_tables

Revision ID: 68dcb508d717
Revises: e29a7e7ee41d
Create Date: 2019-11-03 19:55:38.448342

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '68dcb508d717'
down_revision = 'e29a7e7ee41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.alter_column('description',
                              existing_type=sa.VARCHAR(length=120),
                              nullable=False)

    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.drop_column('type_id')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=80),
                              nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.VARCHAR(length=80),
                              nullable=True)

    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('type_id', sa.VARCHAR(length=64), server_default=sa.text("'MAIN'"), nullable=False))

    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.alter_column('description',
                              existing_type=sa.VARCHAR(length=120),
                              nullable=True)

    # ### end Alembic commands ###
