"""site_tables

Revision ID: 75bdea7372e2
Revises: 68dcb508d717
Create Date: 2019-11-03 19:59:39.415076

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '75bdea7372e2'
down_revision = '68dcb508d717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.alter_column('type',
                              existing_type=sa.VARCHAR(length=64),
                              nullable=True)

    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.alter_column('type',
                              existing_type=sa.VARCHAR(length=64),
                              nullable=False)

    # ### end Alembic commands ###
