"""site_tables

Revision ID: e29a7e7ee41d
Revises: 3473f3973bf8
Create Date: 2019-11-03 10:14:51.423123

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e29a7e7ee41d'
down_revision = '3473f3973bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('option', sa.Column('type_id', sa.String(length=64), nullable=False, server_default='MAIN'))
    op.drop_constraint(None, 'option', type_='foreignkey')
    op.create_foreign_key(None, 'option', 'food_item', ['type_id'], ['type'])
    op.drop_column('option', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('type', sa.VARCHAR(length=64), nullable=False))
    op.drop_constraint(None, 'option', type_='foreignkey')
    op.create_foreign_key(None, 'option', 'food_item', ['type'], ['type'])
    op.drop_column('option', 'type_id')
    # ### end Alembic commands ###
